# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Org1eT-81f6EeotrSG7_xyhKOvm44HCj
"""

class Agente:
    def __init__(self, atividade):
        self.atividade = atividade

    def getAtividade(self):
        max_utilidade = float('-inf')
        melhor_atividade = None
        for atividade, utilidade in self.atividade.items():
            if utilidade > max_utilidade:
                max_utilidade = utilidade
                melhor_atividade = atividade
        return melhor_atividade

# Exemplo de usabilidade
atividade = {
    "Estudar": 10,
    "Assistir TV": 5,
    "Sair com amigos": 8,
    "Dormir": 12
}

agente = Agente(atividade)
obter_atividade = agente.getAtividade()
print("Atividade escolhida pelo agente:", obter_atividade)